### ISSUE TITLE
Cannot launch TiddlyWiki with MultiUser plugin on Windows 10

### ISSUE THREAD

**Issue by zimiarh** [OokTech/TW5-MultiUser#12]
Thanks a lot for keep updating this plugin. This plugin is really great and it is good to see that it gets new features frequently.

However, lately I found that I cannot launch TiddlyWiki with this plugin on Windows. To be more specifically, when I try to launch the latest version (b770c46b6c665f3c309b2546774c97a505d7b94a) with command `node.exe .\tiddlywiki.js .\path\to\wiki --wsserver`, I get an message `Error: Unknown command: wsserver`. For your information, I was able to use it to launch the version with git commit 0e3c5632205ac88f10e333e8e060494176042dc1.

Environment specs:
- OS: Windows 10
- Shell: PowerShell
- TiddlyWiki: v5.1.16-prerelease
- node: v8.9.3

**Comment by inmysocks** [comment]
If it doesn't know the wsserver command than the problem is probably that it can't find the plugin.

The plugin must either be with the other plugins in the plugins subfolder of where the tiddlywiki.js file is or the location of the plugins folder needs to be added as an environment variable. I am not sure how you set environment variables in windows.

The folder for the plugin must be called MultiUser, not TW5-MultiUser (this is a change between the two commits you mentioned above), and it has to be listed this way in the tiddlywiki.info file for your wiki.

Hopefully some part of that should help.

**Comment by zimiarh** [comment]
Ah! I did not notice that the plugin name changed. Rename the folder to MultiUser solved the problem. Thanks a lot!
